# Generated by Django 5.2.7 on 2025-10-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('buy_order', models.CharField(max_length=60, unique=True)),
                ('session_id', models.CharField(max_length=60)),
                ('token_ws', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='initialized', max_length=30)),
                ('authorization_code', models.CharField(blank=True, max_length=40)),
                ('payment_type', models.CharField(blank=True, max_length=10)),
                ('installments_number', models.IntegerField(blank=True, null=True)),
                ('response_raw', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
