# Generated by Django 5.2.7 on 2025-10-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_donation_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(default='initialized', help_text='Estados: initialized, authorized, failed, aborted.', max_length=30),
        ),
    ]
