# Generated by Django 5.2.7 on 2025-10-22 00:27

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[core.validators.validate_rut]),
        ),
    ]
